/**
 * Host-token authentication helpers.
 *
 * The browser-side sessionId is generated once and stored in localStorage;
 * it is not a secret. Calling getRoomByCode with a guessed room code let any
 * attacker harvest every player's sessionId, and from there impersonate the
 * host on endGame / resetGame / populateLines / updateGridSize / updatePartyMode
 * / startGame.
 *
 * This module introduces a server-issued, single-use, per-room hostToken. The
 * token is generated by the server in createRoom, returned to the browser
 * ONCE, and stashed in sessionStorage (cleared on tab close, never persisted
 * across sessions). The server stores only the SHA-256 hash. Host-gated
 * mutations require the caller to present the raw token; the server hashes
 * it and compares.
 *
 * Legacy rooms (created before this deploy) have no hostTokenHash on the
 * room row. The isAuthorisedHost helper falls back to the previous
 * sessionId-only check for those rooms, so the deploy does not break
 * in-flight games. New rooms always have a hostTokenHash and require the
 * token.
 *
 * @module convex/auth/token
 */

const TOKEN_BYTES = 32; // 256 bits of entropy

/**
 * Generate a cryptographically-random host token. Returns a 64-char hex
 * string (256 bits). Uses crypto.getRandomValues, which is available in
 * the Convex runtime and in modern browsers.
 *
 * @returns {string} 64-char hex string
 */
export function generateHostToken() {
    const bytes = new Uint8Array(TOKEN_BYTES);
    crypto.getRandomValues(bytes);
    return Array.from(bytes, (byte) => byte.toString(16).padStart(2, '0')).join('');
}

/**
 * Hash a host token with SHA-256. Returns a 64-char hex string. Returns
 * null for non-string or empty inputs so callers can short-circuit.
 *
 * @param {string} token
 * @returns {Promise<string|null>}
 */
export async function hashToken(token) {
    if (typeof token !== 'string' || token.length === 0) {
        return null;
    }
    const data = new TextEncoder().encode(token);
    const digest = await crypto.subtle.digest('SHA-256', data);
    return Array.from(new Uint8Array(digest), (byte) => byte.toString(16).padStart(2, '0')).join(
        ''
    );
}

/**
 * Constant-time string equality. Avoids early-exit timing leaks when
 * comparing attacker-influenced token hashes against the server's stored
 * hash. Returns false for non-string inputs.
 *
 * @param {string} a
 * @param {string} b
 * @returns {boolean}
 */
export function timingSafeEqual(a, b) {
    if (typeof a !== 'string' || typeof b !== 'string' || a.length !== b.length) {
        return false;
    }
    let mismatch = 0;
    for (let i = 0; i < a.length; i++) {
        mismatch |= a.charCodeAt(i) ^ b.charCodeAt(i);
    }
    return mismatch === 0;
}

/**
 * Decide whether a (sessionId, presentedTokenHash) pair is authorised to
 * perform host-gated actions on a given room. The sessionId must always
 * match the room's hostPlayerId (defense in depth: the browser holds the
 * sessionId in localStorage, but the hostToken is a separate per-tab
 * credential).
 *
 * For rooms with a hostTokenHash (new scheme): the caller's hash must match.
 * For rooms without (legacy): the sessionId match is sufficient.
 *
 * @param {{ hostPlayerId?: string, hostTokenHash?: string }|null|undefined} room
 * @param {string|undefined} sessionId
 * @param {string|undefined} presentedTokenHash  SHA-256 of the raw hostToken the caller presented
 * @returns {boolean}
 */
export function isAuthorisedHost(room, sessionId, presentedTokenHash) {
    if (!room || typeof room.hostPlayerId !== 'string') {
        return false;
    }
    if (typeof sessionId !== 'string' || sessionId !== room.hostPlayerId) {
        return false;
    }
    if (typeof room.hostTokenHash === 'string' && room.hostTokenHash.length > 0) {
        // New scheme: token is mandatory
        if (typeof presentedTokenHash !== 'string' || presentedTokenHash.length === 0) {
            return false;
        }
        return timingSafeEqual(presentedTokenHash, room.hostTokenHash);
    }
    // Legacy room: no token recorded. sessionId match is sufficient.
    return true;
}

/**
 * Async variant of isAuthorisedHost that accepts the RAW hostToken (not
 * the hash) and hashes it internally. Use this in mutation handlers so
 * the browser does not need to know about the hash function.
 *
 * @param {{ hostPlayerId?: string, hostTokenHash?: string }|null|undefined} room
 * @param {string|undefined} sessionId
 * @param {string|undefined} rawHostToken
 * @returns {Promise<boolean>}
 */
export async function isAuthorisedHostAsync(room, sessionId, rawHostToken) {
    if (typeof rawHostToken === 'string' && rawHostToken.length > 0) {
        const presentedHash = await hashToken(rawHostToken);
        if (presentedHash === null) {
            return false;
        }
        return isAuthorisedHost(room, sessionId, presentedHash);
    }
    return isAuthorisedHost(room, sessionId, undefined);
}

/**
 * Build a public projection of a room row. Strips the hostTokenHash and
 * hostPlayerId (the latter is the host's sessionId, which we no longer
 * leak via the public API). Adds a server-computed isHost boolean when a
 * requestingSessionId is provided.
 *
 * @param {object|null|undefined} room
 * @param {string} [requestingSessionId]
 * @returns {object|null}
 */
export function projectRoomForClient(room, requestingSessionId) {
    if (!room) return null;
    const projection = { ...room };
    const isHost =
        typeof requestingSessionId === 'string' &&
        requestingSessionId.length > 0 &&
        room.hostPlayerId === requestingSessionId;
    delete projection.hostTokenHash;
    delete projection.hostPlayerId;
    projection.isHost = isHost;
    return projection;
}

/**
 * Build a public projection of a list of player rows. Strips sessionId
 * (each player's sessionId is no longer leaked). Adds a server-computed
 * isYou boolean when a requestingSessionId is provided, so the browser
 * can identify its own row without holding a sessionId→playerId map.
 *
 * @param {Array<object>|null|undefined} players
 * @param {string} [requestingSessionId]
 * @returns {Array<object>}
 */
export function projectPlayersForClient(players, requestingSessionId) {
    if (!Array.isArray(players)) return [];
    return players.map((player) => {
        const projection = { ...player };
        const isYou =
            typeof requestingSessionId === 'string' &&
            requestingSessionId.length > 0 &&
            player.sessionId === requestingSessionId;
        delete projection.sessionId;
        projection.isYou = isYou;
        return projection;
    });
}
